
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class frmMain extends javax.swing.JFrame {

 
    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        setTanggal();
        setJam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labeltanggal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        waktulb = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ig = new javax.swing.JButton();
        ns = new javax.swing.JButton();
        ag = new javax.swing.JButton();
        sb = new javax.swing.JButton();
        ck = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ec = new javax.swing.JButton();
        et = new javax.swing.JButton();
        ej = new javax.swing.JButton();
        spb = new javax.swing.JButton();
        kp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtrans = new javax.swing.JTable();
        hapus = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jumlah = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lal = new javax.swing.JLabel();
        dis = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("RESTORAN ENAK");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 10, 260, 50);

        jLabel4.setText("Tanggal");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(520, 10, 70, 20);
        jPanel1.add(labeltanggal);
        labeltanggal.setBounds(590, 10, 110, 20);

        jLabel5.setText("Waktu");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(520, 40, 80, 20);
        jPanel1.add(waktulb);
        waktulb.setBounds(590, 40, 120, 20);

        jPanel4.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.add(jPanel4);
        jPanel4.setBounds(490, 0, 300, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 70);

        jLabel2.setFont(new java.awt.Font("News701 BT", 0, 14)); // NOI18N
        jLabel2.setText("MAKANAN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 80, 100, 30);

        ig.setBackground(new java.awt.Color(255, 204, 255));
        ig.setText("IGA BAKAR");
        ig.setMaximumSize(null);
        ig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igActionPerformed(evt);
            }
        });
        getContentPane().add(ig);
        ig.setBounds(20, 270, 120, 40);

        ns.setBackground(new java.awt.Color(255, 204, 255));
        ns.setText("NASI GORENG");
        ns.setMaximumSize(null);
        ns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nsActionPerformed(evt);
            }
        });
        getContentPane().add(ns);
        ns.setBounds(20, 120, 120, 40);

        ag.setBackground(new java.awt.Color(255, 204, 255));
        ag.setText("AYAM GORENG");
        ag.setMaximumSize(null);
        ag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agActionPerformed(evt);
            }
        });
        getContentPane().add(ag);
        ag.setBounds(20, 170, 120, 40);

        sb.setBackground(new java.awt.Color(255, 204, 255));
        sb.setText("SOP BUNTUT");
        sb.setMaximumSize(null);
        sb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbActionPerformed(evt);
            }
        });
        getContentPane().add(sb);
        sb.setBounds(20, 220, 120, 40);

        ck.setBackground(new java.awt.Color(255, 204, 255));
        ck.setText("CAH KANGKUNG");
        ck.setMaximumSize(null);
        ck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckActionPerformed(evt);
            }
        });
        getContentPane().add(ck);
        ck.setBounds(20, 320, 120, 40);

        jLabel3.setFont(new java.awt.Font("News701 BT", 0, 14)); // NOI18N
        jLabel3.setText("MINUMAN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 80, 100, 30);

        ec.setBackground(new java.awt.Color(255, 204, 204));
        ec.setText("ES CAPUCINO");
        ec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecActionPerformed(evt);
            }
        });
        getContentPane().add(ec);
        ec.setBounds(200, 270, 120, 40);

        et.setBackground(new java.awt.Color(255, 204, 204));
        et.setText("ES TEH");
        et.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etActionPerformed(evt);
            }
        });
        getContentPane().add(et);
        et.setBounds(200, 120, 120, 40);

        ej.setBackground(new java.awt.Color(255, 204, 204));
        ej.setText("ES JERUK");
        ej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejActionPerformed(evt);
            }
        });
        getContentPane().add(ej);
        ej.setBounds(200, 170, 120, 40);

        spb.setBackground(new java.awt.Color(255, 204, 204));
        spb.setText("SOP BUAH");
        spb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spbActionPerformed(evt);
            }
        });
        getContentPane().add(spb);
        spb.setBounds(200, 220, 120, 40);

        kp.setBackground(new java.awt.Color(255, 204, 204));
        kp.setText("KOPI");
        kp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kpActionPerformed(evt);
            }
        });
        getContentPane().add(kp);
        kp.setBounds(200, 320, 120, 40);

        tbtrans.setBackground(new java.awt.Color(120, 201, 209));
        tbtrans.setForeground(new java.awt.Color(0, 102, 102));
        tbtrans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NO", "MENU", "HARGA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbtrans);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(370, 130, 390, 190);

        hapus.setBackground(new java.awt.Color(255, 102, 102));
        hapus.setText("DELETE");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(380, 80, 120, 40);

        jButton1.setBackground(new java.awt.Color(204, 204, 0));
        jButton1.setText("REFRESH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(510, 80, 110, 40);

        jButton2.setBackground(new java.awt.Color(255, 153, 255));
        jButton2.setText("PRINT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(640, 80, 110, 40);

        jButton3.setText("TOTAL ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(360, 330, 90, 50);

        jumlah.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jumlah);
        jumlah.setBounds(460, 330, 90, 50);

        jPanel2.setBackground(new java.awt.Color(183, 226, 226));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 170, 400);

        jPanel3.setBackground(new java.awt.Color(162, 209, 209));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(170, 70, 180, 400);

        lal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(lal);
        lal.setBounds(550, 360, 240, 30);

        dis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(dis);
        dis.setBounds(550, 330, 240, 30);

        jPanel5.setBackground(new java.awt.Color(183, 226, 226));
        getContentPane().add(jPanel5);
        jPanel5.setBounds(350, 70, 440, 400);

        setBounds(0, 0, 804, 439);
    }// </editor-fold>//GEN-END:initComponents
           public void setTanggal(){
    java.util.Date skrg = new java.util.Date();
    java.text.SimpleDateFormat kal = new
    java.text.SimpleDateFormat("dd/MM/yyyy");
    labeltanggal.setText(kal.format(skrg));
    }
           
           public void setJam(){
ActionListener taskPerformer = new ActionListener() {

public void actionPerformed(ActionEvent evt) {
String nol_jam = "", nol_menit = "",nol_detik = "";

java.util.Date dateTime = new java.util.Date();
int nilai_jam = dateTime.getHours();
int nilai_menit = dateTime.getMinutes();
int nilai_detik = dateTime.getSeconds();

if(nilai_jam <= 9) nol_jam= "0";
if(nilai_menit <= 9) nol_menit= "0";
if(nilai_detik <= 9) nol_detik= "0";

String waktu = nol_jam + Integer.toString(nilai_jam);
String menit = nol_menit + Integer.toString(nilai_menit);
String detik = nol_detik + Integer.toString(nilai_detik);

waktulb.setText(waktu+":"+menit+":"+detik+"");
}
};
new Timer(1000, taskPerformer).start();
}
    
          
           
    private void nsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nsActionPerformed
        // TODO add your handling code here:
         String SQL = "INSERT INTO transaksi(menu,harga) " + "VALUES('"+"NASI GORENG"+"','"+"15000"+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahakan", "Sukses", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_nsActionPerformed

    private void agActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agActionPerformed
        // TODO add your handling code here:
        String SQL = "INSERT INTO transaksi(menu, harga) " + "VALUES('"+"AYAM GORENG"+"','"+"17000"+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahakan", "Sukses", JOptionPane.WARNING_MESSAGE);
            }
        
    }//GEN-LAST:event_agActionPerformed

    private void sbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbActionPerformed
        // TODO add your handling code here:
        
        String SQL = "INSERT INTO transaksi(menu, harga) " + "VALUES('"+"SOP BUNTUT"+"','"+"35500"+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahakan", "Sukses", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_sbActionPerformed

    private void igActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igActionPerformed
        // TODO add your handling code here:
        String SQL = "INSERT INTO transaksi(menu, harga) " + "VALUES('"+"IGA BAKAR"+"','"+"55000"+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahakan", "Sukses", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_igActionPerformed

    private void ckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckActionPerformed
        // TODO add your handling code here:
        String SQL = "INSERT INTO transaksi(menu, harga) " + "VALUES('"+"CAH KANGKUNG"+"','"+"10000"+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahakan", "Sukses", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_ckActionPerformed

    private void etActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etActionPerformed
        // TODO add your handling code here:
        String SQL = "INSERT INTO transaksi(menu, harga) " + "VALUES('"+"ES TEH"+"','"+"5000"+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahakan", "Sukses", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_etActionPerformed

    private void ejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejActionPerformed
        // TODO add your handling code here:
        String SQL = "INSERT INTO transaksi(menu, harga) " + "VALUES('"+"ES JERUK"+"','"+"6000"+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahakan", "Sukses", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_ejActionPerformed

    private void spbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spbActionPerformed
        // TODO add your handling code here:
        String SQL = "INSERT INTO transaksi(menu, harga) " + "VALUES('"+"SOP BUAH"+"','"+"9000"+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahakan", "Sukses", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_spbActionPerformed

    private void ecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecActionPerformed
        // TODO add your handling code here:
        String SQL = "INSERT INTO transaksi(menu, harga) " + "VALUES('"+"ES CAPUCINO"+"','"+"8000"+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahakan", "Sukses", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_ecActionPerformed

    private void kpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kpActionPerformed
        // TODO add your handling code here:
        String SQL = "INSERT INTO transaksi(menu, harga) " + "VALUES('"+"KOPI"+"','"+"7000"+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahakan", "Sukses", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_kpActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
       int baris = tbtrans.getSelectedRow();
       if (baris != -1) {
           String NO = tbtrans.getValueAt(baris, 0).toString();
           String SQL = "DELETE FROM transaksi WHERE NO='"+NO+"'";
           int status = KoneksiDB.execute(SQL);
           if (status==1){
           JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
           selectData();
           } else {
               JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
           }
       } else {
           JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
       }
        
    }//GEN-LAST:event_hapusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        selectData();
        
        lal.setText("");
        dis.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("RESTORAN");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}       ");
       try {
           tbtrans.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
       } catch (java.awt.print.PrinterException e) {
           System.err.format("Cannot print %s%n", e.getMessage());
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       double total = 0, diskon = 0, jml = 0;
        
        for (int i = 0; i < tbtrans.getRowCount(); i++) {
            total = total + Double.parseDouble(tbtrans.getValueAt(i, 2).toString());
           diskon = total*20/100;
           jml = total-diskon;
        }
        if(total<200000){
        jumlah.setText(String.valueOf(total));
        } 
        else if(total>=200000){
        jumlah.setText(String.valueOf(jml));
        dis.setText("SELAMAT MENDAPAT DISKON 20%");
        lal.setText("Sebesar : "+diskon);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed
    
 
    
     private void selectData() {
       String kolom[] = {"NO","MENU","HARGA"};
           DefaultTableModel dtm = new DefaultTableModel(null, kolom); 
           String SQL = "SELECT * FROM transaksi";
           ResultSet rs = KoneksiDB.executeQuery(SQL);
           try {
               while(rs.next()) {
               String NO = rs.getString(1);
               String MENU = rs.getString(2);
               String HARGA = rs.getString(3);
               String data[] = {NO,MENU,HARGA};
               dtm.addRow(data);
               }
           } catch (SQLException ex) {
               Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
           }
          tbtrans.setModel(dtm);
           
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ag;
    private javax.swing.JButton ck;
    private javax.swing.JLabel dis;
    private javax.swing.JButton ec;
    private javax.swing.JButton ej;
    private javax.swing.JButton et;
    private javax.swing.JButton hapus;
    private javax.swing.JButton ig;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jumlah;
    private javax.swing.JButton kp;
    private javax.swing.JLabel labeltanggal;
    private javax.swing.JLabel lal;
    private javax.swing.JButton ns;
    private javax.swing.JButton sb;
    private javax.swing.JButton spb;
    private javax.swing.JTable tbtrans;
    private javax.swing.JLabel waktulb;
    // End of variables declaration//GEN-END:variables

   
}
